orderall/routes/web.php
<?php

// INSPECTED ROUTES
Route::group(['middleware' => ['auth']], function() {
  Route::group(['middleware' => ['checkpermissions']], function() {

      // ADMIN
      Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function() {

          // USERS
          Route::resource('user', 'UserController', ['as' => 'admin']);
              Route::get('user/{user}/toggle-role', 'UserController@toggleRole', ['as' => 'admin'])->name('admin.user.toggle-role');
              Route::get('user/{user}/set-business', 'UserController@setBusiness', ['as' => 'admin'])->name('admin.user.set-business');

          // ROLES
          Route::resource('role', 'RoleController', ['except' => ['destroy'], 'as' => 'admin']);
          Route::get('update-developer-permissions', 'RoleController@updateDeveloperPermissions')->name('admin.role.update-developer-permissions');

          // MODULES
          Route::resource('module', 'ModuleController', ['only' => ['index','store'], 'as' => 'admin']);
      });

      // ACCOUNT
      Route::resource('account', 'AccountController', ['only' => ['index','update','destroy']]);
          // Reviews by account
          Route::get('account/reviews', 'AccountController@reviews')->name('account.view-reviews');

      // BUSINESS
      Route::resource('businesses', 'BusinessController', ['except' => ['show']]);
          // Businesses' transactions
          Route::get('businesses/{business}/transactions', 'BusinessController@transactions')->name('businesses.transactions');
          Route::get('businesses/{business}/transactions/{transaction}', 'BusinessController@transaction')->name('businesses.transaction');


      // MENUS
      Route::resource('businesses/{business}/menus', 'MenuController', ['except' => ['show', 'index']]);

      // MENU ITEMS
      Route::resource('businesses/{business}/menuitems', 'MenuItemController', ['except' => ['show', 'index']]);

      // MENU EXTRAS
      Route::resource('businesses/{business}/menuitems/{menuitem}/menuextras', 'MenuExtraController');

      Route::resource('businesses/{business}/menuitems/{menuitem}/menuextracategories', 'MenuExtraCategoryController');

      // REVIEWS
      Route::resource('businesses/{business}/menuitems/{menuitem}/reviews', 'ReviewController', ['only' => ['store', 'create']]);

      // TRANSACTIONS
      Route::resource('transactions', 'TransactionController', ['only' => ['index', 'show']]);


  });
  Route::get('/setphone', function() {
    return view('users/addphone');
  });
  Route::post('/updatephone', 'AccountController@updatephone');
  Route::get('/updatephone/send', function () {
    return view('users.phonecheck');
  });
  Route::get('/subscribe', 'UserEmailController@subscribe');
  Route::get('/cartitems/destroy/{id}', 'CartItemController@destroy');
  Route::get('/cartitems/edit/{id}', 'CartItemController@edit');
  Route::get('/checknotifications', 'TransactionController@checknotifications');
  Route::get('/cartextras/add/{id}/{itemid}', 'CartExtraController@add');
  Route::get('/cartextras/destroy/{id}/{itemid}', 'CartExtraController@destroy');
  Route::get('/confirm/{businessid}', 'AccountController@confirm');

  Route::post('/updatephone/check', 'AccountController@checkphone')->name('updatephone.check');
  Route::post('/cartitems/add', 'CartItemController@add')->name('cartitems.add');
  Route::post('/cartitems/setcomments/{id}', 'CartItemController@setcomments');
  Route::post('/finish', 'TransactionController@store');
});
// UNINSPECTED ROUTES

Route::get('/confirmaccount/{token}', 'UserEmailController@authenticate');
Route::get('/unsubscribe/{value}', 'UserEmailController@unsubscribe');

// Reviews by Menu item
Route::get('businesses/{business}/menuitems/{menuitem}/reviews', 'MenuItemController@reviews')->name('menuitems.view-reviews');
Route::get('/', 'HomeController@main')->name('main');

Route::get('/partner', function () {
    return view('partner');
});
Route::get('/help', function () {
    return view('help');
});
Route::get('/tos', function () {
    return view('tos');
});

Route::get('/business-tos', function () {
    return view('business_tos');
});

Route::get('/privacy', function () {
    return view('privacy');
});

Route::get('/requestbusiness', function () {
    return view('requestbusiness');
});

Route::get('/business-guide', function() {
    return view('business_guide');
});

Route::get('/business-evidence', function() {
    return view('business_evidence');
});

Route::get('/business-about', function() {
    return view('about_business');
});

Route::get('/contact', 'ContactController@view');

Route::post('/contact/send', 'ContactController@send');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('businesses', 'BusinessController', ['only' => ['show']]);
Route::resource('businesses/{business}/menuitems', 'MenuItemController', ['only' => ['show']]);
Route::resource('businesses/{business}/menus', 'MenuController', ['only' => ['show']]);

Auth::routes();

Route::get('register-business', 'Auth\BusinessRegisterController@showRegistrationForm')->name('register-business');
Route::post('register-business', 'Auth\BusinessRegisterController@register');

// Route::get('file-upload', 'FileController@fileUpload');
// Route::post('file-upload', 'FileController@fileUploadPost')->name('fileUploadPost');


Route::get('/search', 'BusinessController@index')->name('businesses.search');
Route::get('/tags/{tag}', 'BusinessController@tags')->name('businesses.tags');

Route::post('/getaddresscoords', 'HomeController@getaddresscoords');

orderall/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laratrust\Traits\LaratrustUserTrait;
use Laratrust;
use Carbon\Carbon;
use NotificationChannels\WebPush\HasPushSubscriptions;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use Notifiable;
    use HasPushSubscriptions;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'email_token', 'business_id', 'phone', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    // RELATIONS
    public function business()
    {
      return $this->belongsTo('App\Business');
    }

    public function transactions()
    {
      return $this->hasMany('App\Transaction', 'user_id');
    }

    public function transaction_items()
    {
      return $this->hasManyThrough('App\TransactionItem', 'App\Transaction')->whereHas('transaction', function ($q) {
        $q->where('status', 'accepted');
      });
    }

    public function carts()
    {
      return $this->hasMany('App\Cart');
    }

    public function reviews()
    {
      return $this->hasMany('App\Review');
    }

    // SCOPES
    public function scopeSearch($query, $column, $value)
    {
      return $query->where($column, 'LIKE', "%$value%");
    }

    public function scopeDevelopers($query)
    {
      return $query->where('developer', 1);
    }

    // ATTRIBUTES
    public function getEditableAttribute()
    {
        return !$this->developer;
    }

    public function getDeleteableAttribute()
    {
        return $this->editable;
    }

    public function getNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    // PERMISSION CHECKS
    public function canEditBusiness($business)
    {
      if(!$business)
        return false;

      return $this->can('businesses.edit') && ($business->owns($this) || $this->hasRole(['Admin', 'Developer']));
    }

    public function canDeleteBusiness($business)
    {
      if(!$business)
        return false;

      return $this->can('businesses.delete') && ($business->owns($this) || $this->hasRole(['Admin', 'Developer']));
    }

    public function canCreateBusiness()
    {
      return $this->can('businesses.create');
    }

    public function canReviewItem($item)
    {
      if ($this->developer) {
        return true;
      }
      else {
        $id = ctype_digit($item) ? $item : $item->id;
        return $this->can('reviews.create') && $this->transaction_items->pluck('menu_item_id')->contains($id);
      }
    }

    // UTILITIES
    public function canMakeTransaction()
    {
      $transaction = $this->transactions()->orderByDesc('created_at')->first();

      if($transaction == null)
        return true;

      if($transaction->created_at->addMinutes(2)->lte(Carbon::now()))
        return true;

      return false;
    }

}

orderall/app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\User;
use App\Role;
use App\Http\Requests\Admin\UserCreateRequest;
use App\Http\Requests\Admin\UserUpdateRequest;
use App\Http\Requests\Admin\ToggleUserRoleRequest;

use Auth;
use DB;
use Input;
use Mail;
use App\Mail\PermissionChanged;

class UserController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = collect();

        if($request->has('search')){
            $users = User::search('email', $request->search)
                ->where('id', '!=', Auth::user()->id)
                ->simplePaginate(20)
                ->appends(Input::except('page'));
        }

        if ($request->ajax() || $request->wantsJson()) {
            return $users;
        }

        return view('admin.user.index')
            ->withRoles(Role::togglableRoles()->get())
            ->withUsers($users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create')
            ->withRoles(Role::userRoles()->pluck('name','id'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserCreateRequest $request)
    {
        $user = User::create($request->all());
        $user->attachRole($request->role);

        flash()->success('User '.$user->name.' created');
        return redirect(route('admin.user.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('admin.user.show')
            ->withUser($user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.user.edit')
            ->withUser($user)
            ->withRoles(Role::userRoles()->pluck('name','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, User $user)
    {
        if (!$user->editable) {
            flash()->error('Can not edit this user');
            return response()->view('errors.403', [], 403);
        }

        $user->update($request->all());
        if($request->role){
            DB::table('role_user')->where('role_user.user_id',$user->id)->delete();
            $user->attachRole($request->role);
        }

        flash()->success('User updated');
        return redirect(route('admin.user.edit', $user->id));
    }


    public function toggleRole(ToggleUserRoleRequest $request)
    {
        $user = User::findOrFail($request->user_id);

        DB::table('role_user')->where('role_user.user_id',$user->id)->delete();

        $role = Role::find($request->role_id);
        $user->attachRole($role->id);

        if ($role->name != 'Business') {
            $user->update(['business_id' => null]);
        }
        flash()->success('Set user '.$user->name.' role to '.$role->name);
        Mail::to($user)->send(new PermissionChanged($user));
        return redirect()->back();
    }

    public function setBusiness(Request $request, User $user)
    {

        if (!$user->editable) {
            flash()->error('Can not toggle role for user '.$user->name);
        } else {
            $request->validate([
                'business_id' => 'required|exists:businesses,id'
            ]);

            $user->business_id = $request->business_id;
            $user->save();
            flash()->success('Business is set');
        }

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        if($user->id == Auth::user()->id){
            flash()->error('Can not delete yourself');
            return response()->view('errors.403', [], 403);
        } else if(!$user->deletable) {
            flash()->error('Can not delete this account');
            return response()->view('errors.403', [], 403);
        }

        $name = $user->name;

        $user->delete();
        flash()->success('User ' . $name . ' deleted');
        return redirect()->back();
    }
}

orderall/resources/views/users/addphone.blade.php
@extends('users.master')
@section('page-title', 'Add a mobile phone number')
@section('user-content')
		<div class="partner-content">
			<h3>Add Phone Number</h3>
			<p>Add a phone number to your account<br/>
			so you can get updates about your order by text</p>
			<img src="{{URL::to('images/setphone.svg')}}">
			<div class="search_box search_box_phone ">
				{{ Form::open(array('url' => 'updatephone')) }}
				@include('errors')
  				{{ Form::tel('phone', Input::old('phone'), array('class' => 'form-control', 'maxlength' => '50')) }}
			    {{ Form::submit('Add phone number', array('class' => 'button01 button02')) }}
				{{ Form::close() }}
			</div>
		</div>
@endsection

orderall/resources/views/users/master.blade.php
@extends('layouts.master')

@section('page-title', 'Your Account')
@section('content')
<div class="middle-contact middle-contact-account">
    <div class="container">
        <div class="account-section">
            <div class="row">
                <div class="col-sm-3">
                  <div class="setting">
                      <ul>
                        @php
                          $user = Auth::user();
                        @endphp
                          <li><a href="{{URL::to('/account')}}"><img src="{{asset('images/user-circle-o.svg')}}"/><span>My Profile<span></a></li>
                          @if(count($user->transactions) > 0)
                            <li><a href="{{URL::to('/transactions')}}"><img src="{{asset('images/food.svg')}}"/><span>My Orders<span></a></li>
                          @endif
                          @if(count($user->reviews) > 0)
                          <li><a href="{{URL::to('/account/reviews')}}"><img src="{{asset('images/file-text.svg')}}"/><span>My Reviews<span></a></li>
                          @endif
                          <form id="logout-form" action="{{ route('logout') }}" method="POST" >
                            @csrf
                          <li><img src="{{asset('images/sign-out.svg')}}"/><span><input type="submit" name="logout" value="Logout"><span></a></li>
                          </form>
                      </ul>
                  </div>
                </div>
                <div class="col-sm-9">
                @yield('user-content')
              </div>
            </div>
        </div>
    </div>
</div>
@endsection

orderall/resources/views/users/phonecheck.blade.php
@extends('users.master')
@section('page-title', 'Enter the code we sent you')
@section('user-content')
  <div class="partner-content">
    <h3>Enter your {{config('app.name')}} code</h3>
    <br />
      @include('errors')
      {{ Form::open(['route' => 'updatephone.check']) }}
          <div class="form-group">
                {{ Form::text('code', Input::old('code'), array('class' => 'form-control')) }}
              </div>
        {{ Form::submit('Submit code', ['class' => 'button01 button02']) }}
      {{ Form::close() }}
      @csrf
  </div>
@endsection

orderall/resources/views/users/reviews.blade.php
@extends('users.master')

@section('page-title', 'Your reviews')
@section('user-content')
  <br />
  <h3>Your reviews</h3>
  <script type="text/javascript">
    $(document).ready(function(){
      $('body').on('click', '.review', function(e){
        window.location = $(this).attr("data");
      })
    });
  </script>
  <style media="screen">
    .review {cursor:pointer;}
    .review:hover {color: gray;}
  </style>
  @if(count($reviews) > 0)
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Business</th>
      <th scope="col">Item</th>
      <th scope="col">Rating</th>
      <th scope="col">Content</th>
    </tr>
  </thead>
    @foreach($reviews as $review)
      <tbody>
        <tr class="review" data="{{URL::to('businesses/' . $review->menuitem->menu->business->id . '#' . $review->menu_item_id)}}">
          <td>{{$review->created_at}}</td>
          <td>{{$review->menuitem->menu->business->name}}</td>
          <td>{{$review->menuitem->name}}</a></td>
          <td>{{$review->rating}}/100</td>
          <td>{{$review->content}}</td>
        </tr>
      </tbody>
    @endforeach
  </table>
  {{ $reviews->links() }}
  @else
    <p>You currently do not have any reviews.</p>
  @endif
@endsection

orderall/resources/views/users/show.blade.php
@extends('users.master')
@section('page-title', 'Your Account')
@section('user-content')
                    <div class="profile-detail">
                        <div class="general-info">

                            <h2>User Information</h2>


                            <div class="account-info">
                              @if ($user->roles()->first()->name == 'UnauthUser')
                                <p>Your email address is not verified</p>
                                <p>Check your email inbox to verify</p>
                                <p>If you are a business, please wait while your request is processed.</p>
                              @else
                                <p>{{ucfirst($user->roles()->first()->display_name)}}</p>
                              @endif

                            </div>
                        </div>
                        <div class="account-view">
                            <div class="form-group">
                                <label>Name</label>
                                <span>{{$user->first_name . ' ' . $user->last_name}}</span>
                            </div>
                            <div class="form-group">
                                <label>Email</label>
                                <span>{{$user->email}}</span>
                            </div>
                            @permission('updatephone.check')
                              <div class="form-group">
                                  <label>Phone Number</label>
                                  <span>
                                  @if($user->phone)
                                  {{$user->phone}}
                                  @endif

                                  @if(!$user->phone)
                                  <a class="btn btn-xs btn-primary openbutton" href="{{URL::to('/setphone')}}">Add a phone number to your account</a>
                                  @else
                                  <a class="btn btn-xs btn-primary openbutton" href="{{URL::to('/setphone')}}">Update</a>
                                  @endif
                                  </span>
                              </div>
                            @endpermission
                        </div>

                        <div class="general-info mt100">

                            <h2>Account Preferences</h2>



                        </div>
                        <div class="notification-tabs mt20 ">
                            <span> <img src="{{URL::to('images/envelope.svg')}}" alt=""> &nbsp
                            @if($user->subscribed)
                              <a class="btn btn-xs btn-primary openbutton" href="{{URL::to('/unsubscribe/' . $user->unsub_token)}}">Unsubscribe from all email notifications</a>
                            @else
                              <a class="btn btn-xs btn-primary openbutton" href="{{URL::to('/subscribe')}}">Subscribe to email notifications</a>
                            @endif
                             </span>
                        </div>
                        {{--
                        <div class="notification-tabs mt20 ">
                            <span> <img src="{{URL::to('images/bell.svg')}}" alt=""> &nbsp
                            @if($user->subscribed)
                              <a class="btn btn-xs btn-primary openbutton" href="{{URL::to('/subscription/unsubscribe')}}">Unsubscribe from all email notifications</a>
                            @else
                              <a class="btn btn-xs btn-primary openbutton" href="{{URL::to('/subscription/subscribe')}}">Subscribe to email notifications</a>
                            @endif
                             </span>
                        </div>--}}

                        @if (Auth::user()->deleteable)
                        <div class="notification-tabs mt20">
                            {{ Form::model($user, [
                                'route' => ['account.destroy', $user->id],
                                'method' => 'DELETE',
                            ]) }}
                            <span>
                              <img src="{{URL::to('images/trash-o.svg')}}" class="mr5">
                              {{ Form::submit('Delete account', [
                              'class' => 'btn btn-xs btn-primary openbutton',
                              'onclick' => 'return confirm("Are you sure you want to delete your account?")'
                            ])}}</span>
                            {{ Form::close() }}
                        </div>
                      @endif
                    </div>
@endsection

orderall/resources/views/users/transaction.blade.php
@extends('users.master')
@section('page-title', 'Transaction for ' . $transaction->business->name . ' at ' . $transaction->created_at->format('M d Y, H:i:s'))
@section('user-content')
  <br />
    <div>
      <h3>
        <a href="{{URL::to('/transactions')}}">Transactions</a> / {{$transaction->created_at->format('M d Y, H:i:s')}}
      </h3>

      <table class="table">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th></th>
            <th scope="col">Price</th>
            <th scope="col">Review</th>
          </tr>
        </thead>
        <tbody>
          @if($transaction->items->isNotEmpty())
            @foreach($transaction->items as $item)
            <tr>
              <td><b>{{$item->name}}</b></td>
              <td></td>
              @if($item->discount)
              <td>${{number_format($item->current_price, 2)}}</td>
              @else
              <td>${{$item->price}}</td>
              @endif
              @if($transaction->status == 'accepted' && $item->item)
                @if (!($item->item->reviews->contains('user_id', Auth::user()->id)))
                  <td><a href="{{URL::to('/businesses/' . $item->item->menu->business->id . '/menuitems/' . $item->item->id . '/reviews/create')}}">Add Review</a></td>
                @endif
              @endif
            </tr>
            @if($item->extras->isNotEmpty())
              @foreach($item->extras as $extra)
              <tr>
                <td><i>+{{$extra->name}}</i></td>
                <td></td>
                <td>${{$extra->price}}</td>
              </tr>
              @endforeach
            @endif
            @endforeach
          @endif
        </tbody>
        <thead>
          <tr>
            <th scope="col">Date</th>
            <th scope="col">Business</th>
            <th scope="col">Total</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{$transaction->created_at->format('M d Y, H:i:s')}}</td>
            <td><a href="{{URL::to('/businesses/' . $transaction->business->id)}}">{{$transaction->business->name}}</a></td>
            <td>${{$transaction->price}}</td>
            @if($transaction->status == 'declined')
              <td>{{ucfirst($transaction->status) . ' (' . $transaction->declined_reason . ')'}}</td>
            @else
              <td>{{ucfirst($transaction->status)}}</td>
            @endif
          </tr>
        </tbody>
      </table>
    </div>
@endsection

orderall/resources/views/users/transactions.blade.php
@extends('users.master')
@section('page-title', 'Your Transactions')
@section('user-content')
    <br />
    <h3>Transactions</h3>
    <script type="text/javascript">
      $(document).ready(function(){
        $('body').on('click', '.transaction', function(e){
          window.location = $(this).attr("data");
        })
      });
    </script>
    <style media="screen">
      .transaction {cursor:pointer;}
      .transaction:hover {color: gray;}
    </style>
    @if ($transactions->isNotEmpty())
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Date</th>
            <th scope="col">Business</th>
            <th scope="col">Price</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($transactions as $transaction)
          <tr class="transaction" data="{{route('transactions.show', $transaction->id)}}">
            <td>
              {{$transaction->created_at->format('M d Y, H:i:s')}}
            </td>
            <td>
              {{$transaction->business->name}}
            </td>
            <td>${{$transaction->price}}</td>
            @if($transaction->status == 'declined')
              <td>{{ucfirst($transaction->status) . ' (' . $transaction->declined_reason . ')'}}</td>
            @else
              <td>{{ucfirst($transaction->status)}}</td>
            @endif
          </tr>
          @endforeach
        </tbody>
      </table>

      {{$transactions->links()}}
    @else
      <p>None Found</p>
    @endif
@endsection