orderall/routes/web.php
<?php

// INSPECTED ROUTES
Route::group(['middleware' => ['auth']], function() {
  Route::group(['middleware' => ['checkpermissions']], function() {

      // ADMIN
      Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function() {

          // USERS
          Route::resource('user', 'UserController', ['as' => 'admin']);
              Route::get('user/{user}/toggle-role', 'UserController@toggleRole', ['as' => 'admin'])->name('admin.user.toggle-role');
              Route::get('user/{user}/set-business', 'UserController@setBusiness', ['as' => 'admin'])->name('admin.user.set-business');

          // ROLES
          Route::resource('role', 'RoleController', ['except' => ['destroy'], 'as' => 'admin']);
          Route::get('update-developer-permissions', 'RoleController@updateDeveloperPermissions')->name('admin.role.update-developer-permissions');

          // MODULES
          Route::resource('module', 'ModuleController', ['only' => ['index','store'], 'as' => 'admin']);
      });

      // ACCOUNT
      Route::resource('account', 'AccountController', ['only' => ['index','update','destroy']]);
          // Reviews by account
          Route::get('account/reviews', 'AccountController@reviews')->name('account.view-reviews');

      // BUSINESS
      Route::resource('businesses', 'BusinessController', ['except' => ['show']]);
          // Businesses' transactions
          Route::get('businesses/{business}/transactions', 'BusinessController@transactions')->name('businesses.transactions');
          Route::get('businesses/{business}/transactions/{transaction}', 'BusinessController@transaction')->name('businesses.transaction');


      // MENUS
      Route::resource('businesses/{business}/menus', 'MenuController', ['except' => ['show', 'index']]);

      // MENU ITEMS
      Route::resource('businesses/{business}/menuitems', 'MenuItemController', ['except' => ['show', 'index']]);

      // MENU EXTRAS
      Route::resource('businesses/{business}/menuitems/{menuitem}/menuextras', 'MenuExtraController');

      Route::resource('businesses/{business}/menuitems/{menuitem}/menuextracategories', 'MenuExtraCategoryController');

      // REVIEWS
      Route::resource('businesses/{business}/menuitems/{menuitem}/reviews', 'ReviewController', ['only' => ['store', 'create']]);

      // TRANSACTIONS
      Route::resource('transactions', 'TransactionController', ['only' => ['index', 'show']]);


  });
  Route::get('/setphone', function() {
    return view('users/addphone');
  });
  Route::post('/updatephone', 'AccountController@updatephone');
  Route::get('/updatephone/send', function () {
    return view('users.phonecheck');
  });
  Route::get('/subscribe', 'UserEmailController@subscribe');
  Route::get('/cartitems/destroy/{id}', 'CartItemController@destroy');
  Route::get('/cartitems/edit/{id}', 'CartItemController@edit');
  Route::get('/checknotifications', 'TransactionController@checknotifications');
  Route::get('/cartextras/add/{id}/{itemid}', 'CartExtraController@add');
  Route::get('/cartextras/destroy/{id}/{itemid}', 'CartExtraController@destroy');
  Route::get('/confirm/{businessid}', 'AccountController@confirm');

  Route::post('/updatephone/check', 'AccountController@checkphone')->name('updatephone.check');
  Route::post('/cartitems/add', 'CartItemController@add')->name('cartitems.add');
  Route::post('/cartitems/setcomments/{id}', 'CartItemController@setcomments');
  Route::post('/finish', 'TransactionController@store');
});
// UNINSPECTED ROUTES

Route::get('/confirmaccount/{token}', 'UserEmailController@authenticate');
Route::get('/unsubscribe/{value}', 'UserEmailController@unsubscribe');

// Reviews by Menu item
Route::get('businesses/{business}/menuitems/{menuitem}/reviews', 'MenuItemController@reviews')->name('menuitems.view-reviews');
Route::get('/', 'HomeController@main')->name('main');

Route::get('/partner', function () {
    return view('partner');
});
Route::get('/help', function () {
    return view('help');
});
Route::get('/tos', function () {
    return view('tos');
});

Route::get('/business-tos', function () {
    return view('business_tos');
});

Route::get('/privacy', function () {
    return view('privacy');
});

Route::get('/requestbusiness', function () {
    return view('requestbusiness');
});

Route::get('/business-guide', function() {
    return view('business_guide');
});

Route::get('/business-evidence', function() {
    return view('business_evidence');
});

Route::get('/business-about', function() {
    return view('about_business');
});

Route::get('/contact', 'ContactController@view');

Route::post('/contact/send', 'ContactController@send');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('businesses', 'BusinessController', ['only' => ['show']]);
Route::resource('businesses/{business}/menuitems', 'MenuItemController', ['only' => ['show']]);
Route::resource('businesses/{business}/menus', 'MenuController', ['only' => ['show']]);

Auth::routes();

Route::get('register-business', 'Auth\BusinessRegisterController@showRegistrationForm')->name('register-business');
Route::post('register-business', 'Auth\BusinessRegisterController@register');

// Route::get('file-upload', 'FileController@fileUpload');
// Route::post('file-upload', 'FileController@fileUploadPost')->name('fileUploadPost');


Route::get('/search', 'BusinessController@index')->name('businesses.search');
Route::get('/tags/{tag}', 'BusinessController@tags')->name('businesses.tags');

Route::post('/getaddresscoords', 'HomeController@getaddresscoords');

orderall/resources/views/layouts/footer.blade.php
<footer class="footer">
    <div class="container">
        <a title="Orderall" href="{{route('main')}}" class="footer_logo"><img alt="Orderall logo" src="{{ asset('images/logo-gray.svg') }}"></a>
        <ul class="footer_links">
        <li><a title="Orderall for your business" href="{{URL::to('business-about')}}">Orderall for your business</a></li>
        <li><a title="Request business" href="{{URL::to('requestbusiness')}}">Request a business to be added</a></li>
        <li><a title="Help" href="{{URL::to('help')}}">Help</a></li>
        <li><a title="Contact" href="{{URL::to('contact')}}">Contact</a></li>
        <li><a title="Terms of Service" href="{{URL::to('tos')}}">Terms of Service</a></li>
        <li><a title="Privacy Policy" href="{{URL::to('privacy')}}">Privacy Policy</a></li>
        {{--<li><a title="About" href="{{URL::to('about')}}">About</a></li>--}}
        </ul>
        <ul class="media_icon">
        <li><a title="Facebook" href="{{URL::to('https://www.facebook.com/OrderallApp')}}"><img src="{{asset('images/facebook.svg')}}" class="fa fa-facebook" alt="Facebook"></a></li>
        <li><a title="Twitter" href="{{URL::to('https://www.twitter.com/OrderallApp')}}"><img src="{{asset('images/twitter.svg')}}" class="fa fa-twitter" alt="Twitter"></a></li>
        <li><a title="Instagram" href="{{URL::to('https://www.instagram.com/OrderallApp/')}}"><img src="{{asset('images/instagram.svg')}}" class="fa fa-instagram" alt="Instagram"></a></li>
        {{--<li><a href="{{URL::to('http://www.snapchat.com')}}"><img src="{{asset('images/snapchat-ghost.svg')}}" class="fa fa-snapchat-ghost"></i></a></li>--}}
        </ul>
        <div class="copy_right">&copy; 2018 Orderall. All rights reserved. </div>
    </div>

</footer>

orderall/resources/views/layouts/head.blade.php
<head>
  <meta charset="utf-8">
  <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('apple-touch-icon.png') }}">
  <link rel="apple-touch-icon" type="image/png" sizes="192x192" href="{{ asset('android-chrome-192x192.png') }}">
  <link rel="icon" type="image/png" sizes="256x256" href="{{ asset('android-chrome-256x256.png') }}">
  <link rel="icon" type="image/png" sizes="512x512" href="{{ asset('android-chrome-512x512.png') }}">
  <link rel="icon" type="image/png" sizes="150x150" href="{{ asset('mstile-150x150.png') }}">
  <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('favicon.ico') }}">
  <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('favicon-32x32.png') }}">
  <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('favicon-16x16.png') }}">
  <link rel="manifest" href="{{ asset('site.webmanifest') }}">
  <link rel="mask-icon" href="{{ asset('safari-pinned-tab.svg') }}" color="#5bbad5">
  @stack('styles')
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">
  <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ asset('css/styles.css') }}" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="@yield('meta-description', 'Order from restaurants near you with Orderall. Search for food, choose what you want and pick it up for free.')">
  <meta name="keywords" content="@yield('meta-keywords', 'order, food, search, restaurants')">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#333">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <meta property="og:title" content="@yield('og-title' . ' | Orderall', 'Order from restaurants near you | Orderall')" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="Orderall" />
  <meta property="og:description" content="@yield('og-description', 'Order from restaurants near you with Orderall. Search for food, choose what you want and pick it up for free.')" />
  <meta property="og:url" content="{{URL::current()}}" />
  <meta property="og:image" content="@yield('og-image', asset('android-chrome-512x512.png'))" />
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="{{'@OrderallApp'}}" />
  <meta name="twitter:image" content="@yield('twitter-image', asset('android-chrome-512x512.png'))">
  <meta name="twitter:title" content="@yield('twitter-title' . ' | Orderall', 'Order from restaurants near you | Orderall')">
  <meta name="twitter:description" content="@yield('twitter-description', 'Order from restaurants near you with Orderall. Search for food, choose what you want and pick it up for free.')">
  <script src = "{{URL::to('js/jquery-3.3.1.min.js')}}"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script>window.Laravel = @php echo(json_encode(['csrfToken' => csrf_token()])); @endphp </script>
  <script>var baseUrl = '{{url('/')}}/';</script>
  <title>@yield('page-title', config('app.name')) | {{config('app.name')}}</title>
</head>

orderall/resources/views/layouts/header.blade.php
@php
  $user = Auth::user();
@endphp

<div data-fullsize="{{URL::to('/images/back_img01.jpg')}}" class="progressive-bg top_banner">
  <div class="container">
    <div class="top_navi">
        @if (Auth::check())

        <div class="dropdown pull-right dropdown-session">
          <a title="Accounts" data-target="" href="{{route('account.index')}}" data-toggle="dropdown" class="dropdown-toggle">
          <img alt="Profile" src="{{asset('images/user-circle-o-white.svg')}}" style="user-drag: none;user-select: none;-moz-user-select: none;-webkit-user-drag: none;-webkit-user-select: none;-ms-user-select: none;" class="mr10">{{$user->name}} <b class="caret"></b></a>
          <ul class="dropdown-menu">
              <li><a title="Profile" href="{{route('account.index')}}">Profile</a></li>

              @if ($user->business)
                <li><a title="Your business" href="{{route('businesses.show', $user->business_id)}}">View my business</a></li>

              @elseif ($user->canCreateBusiness())
                <li><a title="Create business" href="{{route('businesses.create')}}">Add my business</a></li>
              @endif

              @if ($user->hasRole(['Admin', 'Developer']))
                <li><a title="Users" href="{{route('admin.user.index')}}">Users</a></li>
              @endif

              @if ($user->hasRole(['Admin', 'Developer']))
                <li><a title="Roles" href="{{URL::to('/admin/role')}}">Roles</a></li>
              @endif

              <form id="logout-form" action="{{ route('logout') }}" method="POST" >
                @csrf
              <li><input type="submit" name="logout" value="Logout"></li>
              </form>
          </ul>
        </div>

        @else
        <ul class="navi">
          <li><a title="Login" href="{{route('login')}}">Login</a></li>
          <li><a title="Register" href="{{route('register')}}">Signup</a></li>
          <li><a title="Register as Business" href="{{url('register-business')}}">Business Signup</a></li>
        </ul>
        @endif

    </div>
    <center class="test">
      <div class="banner_box">
        <a title="Orderall" href="{{route('main')}}" class="logo"><img src="{{ asset('images/logo-white-beta.svg') }}" alt="The {{config('app.name')}} logo"></a>
        <h6>Search for nearby restaurants, cafes and bars</h6>
        <div id="search-form-container">

        </div>
        <div class="search_box">
          <form class="form" id="searchform" action="#" method="GET">
          <img class="search-location" title="Get my location" alt="Get location" src="{{ asset('images/crosshairs.svg') }}" onload="if(sessionStorage.xcoord)$(this).hide()" onclick="autoGeoMethod()" style="cursor: pointer;user-drag: none;user-select: none;-moz-user-select: none;-webkit-user-drag: none;-webkit-user-select: none;-ms-user-select: none;">
          <img class="remove-search" title="Clear my location" alt="Clear location" src="{{ asset('images/cancel-location.svg') }}" onload="if(!(sessionStorage.xcoord))$(this).hide()" onclick="addressMethod()" style="cursor: pointer;user-drag: none;user-select: none;-moz-user-select: none;-webkit-user-drag: none;-webkit-user-select: none;-ms-user-select: none;">
            <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">
            <input type="hidden" name="radius" id="search-radius" value="{{ (isset($radius) ? $radius : 10) }}">
            {{ Form::hidden('xcoord', '0', array('id' => 'xcoord')) }}
            {{ Form::hidden('ycoord', '0', array('id' => 'ycoord')) }}
            <input class="form-control" aria-label="Search" autocomplete="off" id="search" disabled="disabled" type="text" name="search" placeholder="Loading..." @if(isset($search)) value="{{$search}}" @endif maxlength="50" required>
          <input class="search-icon" type="image" src="{{ asset('images/search.svg') }}" style="user-drag: none;user-select: none;-moz-user-select: none;-webkit-user-drag: none;-webkit-user-select: none;-ms-user-select: none;" alt="Submit" />
        </form>
        </div>
      </div>
    </center>

  </div>
</div>
@push('scripts')
  <script src="{{URL::to('js/geolocation-main.js')}}"></script>
@endpush

orderall/resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
@include('layouts.head')
  <body>
    @include('layouts.header')
    @include('flash::message')
    @yield('content')
    @include('layouts.footer')

    @stack('scripts')
    <script defer src = "{{URL::to('js/scripts.js')}}"></script>
    @if(Auth::check())
    <script defer src = "{{URL::to('js/notifications.js')}}"></script>
    @endif
  </body>
</html>

orderall/resources/views/layouts/tagbox.blade.php
@if($business->tags->isNotEmpty())
<div class="tag-box-main">
	<span class="tag-label">Tags:</span>
	<div class="tags-items">
		@foreach($business->tags as  $tag)
			<a class="" href={{route('businesses.tags', $tag->name)}}>
				<label>
					{{$tag->name}} 
				</label>
			</a>
		@endforeach
	</div>
</div>
@endif