orderall/routes/web.php
<?php

// INSPECTED ROUTES
Route::group(['middleware' => ['auth']], function() {
  Route::group(['middleware' => ['checkpermissions']], function() {

      // ADMIN
      Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function() {

          // USERS
          Route::resource('user', 'UserController', ['as' => 'admin']);
              Route::get('user/{user}/toggle-role', 'UserController@toggleRole', ['as' => 'admin'])->name('admin.user.toggle-role');
              Route::get('user/{user}/set-business', 'UserController@setBusiness', ['as' => 'admin'])->name('admin.user.set-business');

          // ROLES
          Route::resource('role', 'RoleController', ['except' => ['destroy'], 'as' => 'admin']);
          Route::get('update-developer-permissions', 'RoleController@updateDeveloperPermissions')->name('admin.role.update-developer-permissions');

          // MODULES
          Route::resource('module', 'ModuleController', ['only' => ['index','store'], 'as' => 'admin']);
      });

      // ACCOUNT
      Route::resource('account', 'AccountController', ['only' => ['index','update','destroy']]);
          // Reviews by account
          Route::get('account/reviews', 'AccountController@reviews')->name('account.view-reviews');

      // BUSINESS
      Route::resource('businesses', 'BusinessController', ['except' => ['show']]);
          // Businesses' transactions
          Route::get('businesses/{business}/transactions', 'BusinessController@transactions')->name('businesses.transactions');
          Route::get('businesses/{business}/transactions/{transaction}', 'BusinessController@transaction')->name('businesses.transaction');


      // MENUS
      Route::resource('businesses/{business}/menus', 'MenuController', ['except' => ['show', 'index']]);

      // MENU ITEMS
      Route::resource('businesses/{business}/menuitems', 'MenuItemController', ['except' => ['show', 'index']]);

      // MENU EXTRAS
      Route::resource('businesses/{business}/menuitems/{menuitem}/menuextras', 'MenuExtraController');

      Route::resource('businesses/{business}/menuitems/{menuitem}/menuextracategories', 'MenuExtraCategoryController');

      // REVIEWS
      Route::resource('businesses/{business}/menuitems/{menuitem}/reviews', 'ReviewController', ['only' => ['store', 'create']]);

      // TRANSACTIONS
      Route::resource('transactions', 'TransactionController', ['only' => ['index', 'show']]);


  });
  Route::get('/setphone', function() {
    return view('users/addphone');
  });
  Route::post('/updatephone', 'AccountController@updatephone');
  Route::get('/updatephone/send', function () {
    return view('users.phonecheck');
  });
  Route::get('/subscribe', 'UserEmailController@subscribe');
  Route::get('/cartitems/destroy/{id}', 'CartItemController@destroy');
  Route::get('/cartitems/edit/{id}', 'CartItemController@edit');
  Route::get('/checknotifications', 'TransactionController@checknotifications');
  Route::get('/cartextras/add/{id}/{itemid}', 'CartExtraController@add');
  Route::get('/cartextras/destroy/{id}/{itemid}', 'CartExtraController@destroy');
  Route::get('/confirm/{businessid}', 'AccountController@confirm');

  Route::post('/updatephone/check', 'AccountController@checkphone')->name('updatephone.check');
  Route::post('/cartitems/add', 'CartItemController@add')->name('cartitems.add');
  Route::post('/cartitems/setcomments/{id}', 'CartItemController@setcomments');
  Route::post('/finish', 'TransactionController@store');
});
// UNINSPECTED ROUTES

Route::get('/confirmaccount/{token}', 'UserEmailController@authenticate');
Route::get('/unsubscribe/{value}', 'UserEmailController@unsubscribe');

// Reviews by Menu item
Route::get('businesses/{business}/menuitems/{menuitem}/reviews', 'MenuItemController@reviews')->name('menuitems.view-reviews');
Route::get('/', 'HomeController@main')->name('main');

Route::get('/partner', function () {
    return view('partner');
});
Route::get('/help', function () {
    return view('help');
});
Route::get('/tos', function () {
    return view('tos');
});

Route::get('/business-tos', function () {
    return view('business_tos');
});

Route::get('/privacy', function () {
    return view('privacy');
});

Route::get('/requestbusiness', function () {
    return view('requestbusiness');
});

Route::get('/business-guide', function() {
    return view('business_guide');
});

Route::get('/business-evidence', function() {
    return view('business_evidence');
});

Route::get('/business-about', function() {
    return view('about_business');
});

Route::get('/contact', 'ContactController@view');

Route::post('/contact/send', 'ContactController@send');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('businesses', 'BusinessController', ['only' => ['show']]);
Route::resource('businesses/{business}/menuitems', 'MenuItemController', ['only' => ['show']]);
Route::resource('businesses/{business}/menus', 'MenuController', ['only' => ['show']]);

Auth::routes();

Route::get('register-business', 'Auth\BusinessRegisterController@showRegistrationForm')->name('register-business');
Route::post('register-business', 'Auth\BusinessRegisterController@register');

// Route::get('file-upload', 'FileController@fileUpload');
// Route::post('file-upload', 'FileController@fileUploadPost')->name('fileUploadPost');


Route::get('/search', 'BusinessController@index')->name('businesses.search');
Route::get('/tags/{tag}', 'BusinessController@tags')->name('businesses.tags');

Route::post('/getaddresscoords', 'HomeController@getaddresscoords');

orderall/app/Cart.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Auth;

class Cart extends Model
{
    public $timestamps = false;
    protected $fillable = ['business_id'];

    //Items in this cart
    public function cartitems()
    {
      return $this->hasMany('App\CartItem');
    }

    //Extras in this cart
    public function cartextras()
    {
      return $this->hasManyThrough('App\CartExtra', 'App\CartItem');
    }

    //The user who owns this cart
    public function user()
    {
      return $this->belongsTo('App\User');
    }

    //The business that this cart belongs to
    public function business()
    {
      return $this->belongsTo('App\Business');
    }

    // Check if cart exists
    public static function exists($user_id, $business_id)
    {
        return self::where([
            'user_id' => $user_id,
            'business_id' => $business_id,
        ])->first();

    }

    public function getOrderableAttribute()
    {
        $result = $this->requiredExtrasChosen();

        // some additional checks could go here

        return $result;
    }

    public function requiredExtrasChosen()
    {
        $result = true;

        foreach($this->cartitems as $cartitem){

            if($cartitem->menuitem->extracategories->isEmpty())
                continue;

            $menuextracategories = $cartitem->menuitem->extracategories;

            foreach ($menuextracategories as $cat) {

                if($cat->menuextras->isEmpty() || !$cat->required)
                    continue;

                foreach ($cat->menuextras as $menuextra) {
                    if($exists = $this->cartextras->firstWhere('menu_extra_id', $menuextra->id)){
                        $result = true;
                        break;
                    } else {
                        $result = false;
                    }
                }
                if($result == false) break;
            }


        }

        return $result;

    }

    // Get cart total
    public function getTotalAttribute()
    {
        $result = $this->cartitems->sum('menuitem.price');
        $result -= $this->cartitems->sum('menuitem.discount');
        $result += $this->cartextras->sum('menuextra.price');

        return $result;
    }

}

orderall/resources/views/carts/cart.blade.php
<div id="cartitems-container">
    <div class="container-fluid">
        <div class="scrollable-cart-sec">
            <div class="clearfix scrollable-cart" id="cart-cartitems" style="display:none;">
              @include('carts.cartitems')
            </div>
        </div>
        <div class="clear" style="cursor:pointer;">
            <div id="cart-orderbutton" class="btn btn-primary orderbutton-cart {{$cart->orderable ? null : 'disabled'}}">
                <div class="display-inline ">
                    <a class="display-inline orderbutton" href={{ URL::to('confirm/' . $cart->business->id)}}>$<span class="totalprice" id="totalprice">
                      {{number_format(($cart->total), 2)}}
                    </span> - Order</a>
                </div>
            </div>
        </div>
    </div>
</div>

orderall/resources/views/carts/cartitem-confirm.blade.php
<div class="cart-box custwidth">
    <div class="row">
        <div class="img-cart-item">
            <div class="imgwrap">
                <img
                        @if($element->image_path)
                        src="{{Storage::url('images/menuitems/'.$element->image_path.'.jpg') }}"
                        @else
                        src="{{asset('images/default.svg')}}"
                        @endif
                        style="width:100%;"alt="">
            </div>

        </div>
        <div class="cartitem-info">
            <div class="cartitem-stuff">
                <h2 class="mb-10 mt-10 font-bold">{{$element->name}}</h2>
                <div class="clear">
                    <span id="itemprice" class="item-price" price="{{$element->price - $element->discount}}">
                        <span class="col-orange v-middle">$</span>
                        <span class="price-no">
                            {{number_format($element->price - $element->discount, 2)}}
                        </span>
                    </span>
                    <span id="extrastotal" class="extras-total" price="{{$cartitem->cartextras->sum('menuextra.price')}}">
                        <span class="col-orange v-middle">+</span>
                        <span class="price-no extras-total-price">
                            {{number_format($cartitem->cartextras->sum('menuextra.price'), 2)}}
                        </span>
                    </span>
                </div>

                <button class="delete-icon" onClick="removeItem(this, {{$cartitem->id}}, $(this).parent().parent())" type="button">
                    <img width="14" src="{{URL::to('/images/close-btn-cart.svg')}}" alt="remove-product">
                </button>
            </div>

        </div>
    </div>
    <div class="form-group comments-box" >
        <input class="form-control" placeholder="Comments" name="comments{{$element->id}}" id="comments{{$element->id}}" value="{{$cartitem->comments}}" type="text" maxlength="127" onfocusout="setcomment({{$cartitem->id}}, this)">
    </div>
    @if (count($element->extras) > 0)
        <div class="extras-add-div show-extras">
            <span class="extras-add-div show-extras">Extras</span>
            <img class="show-extra-arrow comments-arrow show-extras" src="{{asset('images/extra-right-arrow.svg')}}" />
            @if (count($element->extras) > 0)
                <div class="extras-div" style="display:none;">
                    <div id="extras">
                        <table class="extra-table mb-0">
                            @include('carts.categorized-new')
                            @include('carts.uncategorized-new')
                        </table>

                    </div>
                </div>
                <div class="cart-total mt-10 ">
                    <span>Total: $</span>
                    <span class="cartitem-total totalprice" price="{{($element->price - $element->discount) + $cartitem->cartextras->sum('menuextra.price')}}">{{number_format(($element->price - $element->discount) + $cartitem->cartextras->sum('menuextra.price'), 2)}}</span>
                </div>
            @endif
        </div>
    @endif
</div>
<div class="clearfix"></div>

orderall/resources/views/carts/cartitem.blade.php
<div class="cart-box">
    <div class="row">
        <div class="img-cart-item">
            <img
                @if($element->image_path)
                src="{{Storage::url('images/menuitems/'.$element->image_path.'.jpg') }}"
                @else
                src="{{asset('images/default.svg')}}"
                @endif
                style="width:100%;"alt="">
            <div class="comments-up-down">
                <span>Comment</span>
                <img class="comments-arrow flip" src="{{asset('images/extra-right-arrow.svg')}}"/>
            </div>
        </div>
        <div class="cartitem-info">
            <div class="cartitem-stuff">
                <h2 class="mb-10 mt-10 font-bold">{{$element->name}}</h2>
                <div class="clear">
                    <span id="itemprice" class="item-price" price="{{$element->price - $element->discount}}">
                        <span class="col-orange v-middle">$</span>
                        <span class="price-no">
                            {{number_format($element->price - $element->discount, 2)}}
                        </span>
                    </span>
                    <span id="extrastotal" class="extras-total" price="{{$cartitem->cartextras->sum('menuextra.price')}}">
                        <span class="col-orange v-middle">+</span>
                        <span class="price-no extras-total-price">
                            {{number_format($cartitem->cartextras->sum('menuextra.price'), 2)}}
                        </span>
                    </span>
                </div>
                <div class="cart-total mt-10">
                    <span>Total:</span>
                    <span>$</span>
                    <span class="cartitem-total totalprice" price="{{($element->price - $element->discount) + $cartitem->cartextras->sum('menuextra.price')}}">{{number_format(($element->price - $element->discount) + $cartitem->cartextras->sum('menuextra.price'), 2)}}</span>
                </div>
                <button class="delete-icon" onClick="removeItem(this, {{$cartitem->id}}, $(this).parent().parent())" type="button">
                    <img width="14" src="{{URL::to('/images/close-btn-cart.svg')}}" alt="remove-product">
                </button>
            </div>

        </div>
    </div>
    <div class="form-group comments-box" style="display: none;">
        <input class="form-control" placeholder="Comments" name="comments{{$element->id}}" id="comments{{$element->id}}" value="{{$cartitem->comments}}" type="text" maxlength="127" onfocusout="setcomment({{$cartitem->id}}, this)">
    </div>
    @if (count($element->extras) > 0)
    <div class="extras-add-div show-extras">
        <span class="extras-clickable">Extras</span>
        <img class="show-extra-arrow comments-arrow extras-clickable" src="{{asset('images/extra-right-arrow.svg')}}"/>
        @if (count($element->extras) > 0)
        <div class="extras-div" style="display:none;">
            <div id="extras">
                <table class="extra-table mb-0">
                    @include('carts.categorized-new')
                    @include('carts.uncategorized-new')
                </table>
            </div>
        </div>
        @endif
    </div>
    @endif
</div>

orderall/resources/views/carts/cartitems.blade.php
@foreach ($cart->cartitems as $cartitem)
  @php
  $element = $cartitem->menuitem ;
  @endphp
  @include('carts.cartitem')
@endforeach

orderall/resources/views/carts/categorized-new.blade.php
<script type="text/javascript">
  function clearCategory(category, cartitem)
  {
    $('input:radio').each(function(index, element){
      if ($(element).attr('category') == category) {
        element.checked = false;
        addExtraToCart(element, $(element).attr("data"), cartitem);
      }
    });
  }
</script>
@foreach ($element->extras_categorized as $category)
  @if (count($category->menuextras) > 0)
    <tr>
      <th colspan="3" align="center">
        <h5 class="font-bold">{{$category->name}}
          @if($category->required)
            (Choose one)
          @endif

          @if (!$category->required)
            <span class="pull-right close-extra" onclick="clearCategory($(this).attr('category'), {{$cartitem->id}})" category="{{$category->id}}" style="cursor: pointer;">×</span>
          @endif
        </h5>
      </th>
    </tr>
    @foreach ($category->menuextras as $extra)
      <tr class="border-bottom">
        <td width="170">{{$extra->name}}</td>
        <td><span class="col-orange">$</span> <span class="extraprice">{{$extra->price}}</span></td>
        <td style="text-align: right;">
          <label class="rad">
            <input class="menuextra" category="{{$category->id}}" name="menuextra[]-{{$extra->category->id . '-' . $cartitem->id}}"
                   @if ($cartitem->cartextras->contains('menu_extra_id', $extra->id))
                   checked
                   @endif
                   onchange="addExtraToCart(this, {{$extra->id}}, {{$cartitem->id}})"
                   type="radio" data="{{$extra->id}}" price="{{$extra->price}}">
            <i></i>
          </label>
        </td>

      </tr>
    @endforeach
  @endif
@endforeach

orderall/resources/views/carts/uncategorized-new.blade.php
@if ($element->extras_uncategorized)
    <tr>
        <th colspan="3" align="center">
            <h5 class="font-bold">Other Extras</h5>
        </th>
    </tr>
    @foreach($element->extras_uncategorized as $extra)
    <tr class="border-bottom">

      <td width="170">{{$extra->name}}</td>
      <td><span class="col-orange">$</span>{{$extra->price}}</td>
        <td class="new-checkbox">
            <div class="checkbox float-right fl_check ">
                <label>
                    <input price="{{$extra->price}}" class="menuextra float-right" name="{{$extra->name}}" type="checkbox"
                  @if ($cartitem->cartextras->contains('menu_extra_id', $extra->id))
                   checked
                 @endif
                   onchange="addExtraToCart(this, {{$extra->id}}, {{$cartitem->id}})">
                    <i class="helper"></i>
                </label>
            </div>
        </td>
    </tr>
    @endforeach
@endif